server:
  port: 8081

spring:
  application:
    name: ShopApp

  datasource:
   username: user
   password: ${PWD}
   url: jdbc:postgresql://localhost:5432/postgres
   driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: false

app:
  scheduling:
    enable: false
    priceIncreasePercentage: 1.4
    optimization: false

exchange-rate:
  file-name: exchange-rate.json
  base-rate: 100.0

currency-service:
  host: ${CURRENCY_SERVICE_HOST:http://localhost:8080}
  retry: 3
  methods:
    get-currency: /api/v1/currency