server:
  port: 8081

spring:
  application:
    name: ShopApp

  datasource:
    username: user
    password: ${PWD}
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        batch_size: 100000


  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: false

  h2:
    console:
      enabled: false

app:
  scheduling:
    enable: false
    priceIncreasePercentage: 10.1
    optimization: false

exchange-rate:
  file-name: exchange-rate.json


webclient:
  retry: 3
  currency-service:
    host: ${CURRENCY_SERVICE_HOST:http://localhost:8080}
    get-currency: /api/v1/currency

  account-service:
    host: ${ACCOUNT_SERVICE_HOST:http://localhost:8082}
    get-account: /api/v1/account

  crm-service:
    host: ${CRM_SERVICE_HOST:http://localhost:8083}
    get-crm: /api/v1/crm