apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgredb
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/postgres
  storageClassName: standard